session_name: dpcrm
start_directory: ~/dev/
windows:
  - window_name: crm
    focus: true
    panes:
      - shell_command:
          - cd crm
          - nvim
  - window_name: backend
    panes:
      - shell_command:
          - cd techfolio-backend
          - vim
  - window_name: cmd
    panes:
      - shell_command:
          -
  - window_name: server
    layout: main-vertical
    panes:
      - shell_command:
          - cd crm
          - pnpm dev
      - shell_command:
          - cd techfolio-backend
          - ./manage.sh runserver
