set -ga terminal-overrides ",xterm-254color*:Tc"
set -s escape-time 2

set-window-option -g automatic-rename on
set-option -g set-titles on

#unbind C-b

set-option -g prefix C-l
bind-key C-l send-prefix
set -g status-style 'bg=#282C34 fg=#ABB2BF'

bind r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

set -g base-index 1

set-window-option -g mode-keys vi
set -g mode-keys vi
set -g status-keys vi
set -g history-limit 10000

# Shift arrow to switch windows
bind -r Left  previous-window
bind -r Right next-window

# Reload tmux confi
bind -r C-r source-file ~/.tmux.conf

#default open is on curr dir, capital C opens on normal dir
bind c new-window -c "#{pane_current_path}"
bind C new-window

bind -r i last-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @resurrect-strategy-nvim 'session'

run -b '~/.tmux/plugins/tpm/tpm'
